### ISSUE TITLE
Upload a logo

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#212]
In app/components/election-component.js - there is an option to provide a organizationUrl.
We need to provide an an option for the user to upload a url image and save that to cloudinary and then use that url. 
The user should still be able to enter the url directly. 

It might be good to find a package on npm - make sure it's MIT licensed and has a good number of weekly downloads.

**Comment by mattwinne** [comment]
@ddfridley Implemented by uploading the image in the browser, sending to server via websocket (non-stream), and uploading to cloudinary from server. I also looked into ways it could be uploaded entirely from the browser. 

One method is with the cloudinary widget. This only requires sharing the cloud name with the browser (not the api key or api secret). That doesn't seem like too much of a security risk since technically the cloud name is visible / can be inspected in any cloudinary urls we use. This may be the simplest solution if we want to shift to uploading entirely from the frond end.

I also looked into how a one time key can be sent from the server to the client to upload. After reading the cloudinary docs, there is some functionality for this, but as far as I understand this only adds extra security through the addition of SHA authentication signatures, and still requires at a minimum the cloud name to be available at the client. I may look into this more. Perhaps it is a matter of configuring your cloudinary repo settings to only allow uploads that are signed, thus having the cloud name visible is not any security risk.

I added some stylistic decisions in my solution, including displaying the URL once it is uploaded or the URL is added. Please let me know if you have any comments or recommended changes.
