### ISSUE TITLE
PasteGoogleSheetsLink component

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#55]
```
<PastGoogleSheetsLink
    className={}
    style={}
    electionOM={[electionObj,electionMethods]}
>
```
See #46 for electionOM

- [ ] Initially the component renders the button
- [ ] When someone clicks on the button, then it also renders the popup (as well as the button)
- [ ] After the data is imported, it is extracted into an object, and the column names are checked. 
- [ ] If the column names match, and the electionObj.electionTable is empty, add the rows to the table. And, if there is not already a uniqueId column, create one and initialize each row it's own `objectid().toString()`  from 'isomorphic-mongo-objectid'
- [ ] If there is already electionObj.electionTable - then you will have to merge the new data into the existing data.
- [ ] first if there is a uniqueId column in the incoming data, use that to merge the new row with the existing row
- [ ] second - if no uniqueId column in the incoming data, use the email address to merge
- [ ] or third - if no uniqueId and no email match, use the Candidate Name and Office to find a matching row and merge.  - this is the case when the email address is changed.
- [ ] then add new data to the table - make sure each new column gets a uniqueId
- [ ] finally call electionMethods.updateElectionTable(row, objs) with the list of new/updated rows
- [ ] If there is an error, render specific,  helpful information to the bottom of the popup.   Allow the user to upload again, or cancel. 
- [ ] When it says add the data to the table, above - that's a local, working copy of the table.  The call to updateElectionTable will update the real data and cause a rerender of the component that will display it.
**Stretch Goal**
- [ ] If there was no uniqueId column in the google sheet, add the column and populate it with the uniqueIds generated.

figma: https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh/Undebate-Self-Service-Portal?node-id=368%3A5037

![image](https://user-images.githubusercontent.com/3317487/144526167-6d98d45b-7487-4ac5-91e0-93a09a73bbb1.png)
![image](https://user-images.githubusercontent.com/3317487/144526313-2fc2f86f-7ca6-4636-9bef-f3073eb6a0d1.png)

**Comment by ice1080** [comment]
Hey @ddfridley , I believe I have a pretty good picture of how to implement google's oauth for our needs. I had a couple quick questions/comments on this:

1. I'll eventually need to register our app as a google api app so that our users can grant it read-access to; it's necessary for the oauth requests. To do this, I would need the login information for the google account you mentioned, or we'd need to create a separate one just for the app itself.
1. For storybook, I'm thinking we'll need a google drive with several sheets in it that have various access levels to it, so that everyone is able to see these various levels working. For that to work, the person using storybook would have to already be signed in to this google account (or at least have the login info). In the past, I've created google accounts just for automation/testing of various things, so my thoughts are that we do the same here since we don't want this to be the same account mentioned above in question 1. We then add a decorator to the stories, similar to how we did with the upload csv popup, explaining to the storybook user how to login to the google account so they could test these stories as well if they wanted.
1. I am not planning on working on the stretch goal of adding the unique id back to the original spreadsheet within this issue, as this opens up many other questions about how to handle different cases and what assumptions can be made. I'd say we should write a separate issue to handle that in the future.
1. The default implementation that google recommends is adding the api script to the primary index.html page's header. Since the html page does not exist in this project (I assume it's in undebate) and since we only really need the api for this page, I will try to implement this such that it dynamically adds the script only to the page that loads this component so that it also doesn't slow down the load of other pages.

Thoughts or concerns on all this?

**Comment by ice1080** [comment]
Unfortunately I just realized that almost all of my work for today is no longer very useful because I was embedding all of this into the react component itself (which is what many of their docs show). The google api requires your api key to be passed into every request, so anyone would easily be able to see our api key in the network tab. I'm about to push what I've got so that it's saved somewhere, but after that I'll have to convert all this to backend endpoints instead that go off and retrieve the data for the user, which is a bit more difficult to implement. I'll see how far I can get on this tonight.

**Comment by ice1080** [comment]
I think I have a decently clear path for how to do this in the backend. Is there a way to add endpoints to the app? I _believe_ this is done in routes, is that correct?

**Comment by ddfridley** [comment]
@ice1080 If you are using google security tokens, we will need to include a doc, or add to the readme on how to do it.  This is what I have for using gmail with the civil-server and undebates. https://github.com/EnCiv/undebate/blob/master/doc/Install.md#email-setup

Also, ideally each developer would be able to set it up for themselves, using their own google account.  Then I wouldn't have to manage and pass out secure tokens to volunteers.  So far we've been able to do that - but their may come a roadblock.    Are you able to do this from your own google account? 

It is possible to create routes, but for all the api's so far we have been using sockets.  see https://github.com/EnCiv/civil-server#socket-api-directory.  Look at [app/socket-apis/get-election-docs](https://github.com/EnCiv/undebate-ssp/blob/main/app/socket-apis/get-election-docs.js) and [app/socket-apis/__tests__/get-election-docs](https://github.com/EnCiv/undebate-ssp/blob/main/app/socket-apis/__tests__/get-election-docs.js)

I just remembered - if you use routes there isn't an authentication method for it yet. with socket-io authentication is build in.  Just check for this.synuser in the function on the server side. (see the examples).

You can create mock handlers for socket-api's in the app/stories/make-chapter file. There's one their for 'send-password'.  You can create a switch and add another if you need. 

Also look at https://github.com/EnCiv/undebate-ssp/blob/main/stories/script.stories.js for how to create a story using make-chapter. It's cleaner than the usual story pattern.

Look at https://github.com/EnCiv/undebate-ssp/blob/main/app/web-components/qa-create-moderator-recorder.js for an example of creating a manual test for a socket-api on the dev server.  (you also have to make a specific doc with a path: and a unique _id, in iotas.json).

Here is the link to a directory on EnCiv's google drive where you can put sheets for testing - https://drive.google.com/drive/folders/1-8T4XkHmw50uDy-UER_Pxcu9Z90BCqcr?usp=sharing  Anyone should be able to read them.  I gave you permission to write there.  Will that work?

I hope I have caught up on all your questions.  Let me know if I missed anything.  Also - happy to hear your questions on socket-apis so I can improve the docs.

**Comment by ice1080** [comment]
@ddfridley thanks, I believe this answers most of my questions.

Regarding the security tokens, each dev can setup their own which is what I've been doing to continue forward so far. I was initially thinking that we would eventually be switching to the final values, but those really are only needed for the actual deployment (I believe I saw in heroku). I'll update the markdown for this (and mention it in the stories) so that others know how to do it moving forward. 

For the endpoints, using the sockets instead of routes is perfect, and actually addresses some issues I ran into starting work on them last night, so that's great. It's been a while since I used sockets but I believe I've got all the resources I need to re-learn them and figure them out for this. I'll definitely send you any questions though. Auth isn't super necessary for this, as the user has to authenticate through their own google account anyway, but it's probably good to have it regardless.

I'll also see if I can update make-chapter to work for storybook interactions as it currently only handles `<story>.args` and not `<story>.play`.

I'll have to think more about how to write unit tests for this. Since we'll have 2-3 endpoints that all call google endpoints or redirect a tab to google, it may be more difficult. Let me get further to figure out what difficulties there may be around testing. 

And I believe that google drive should work for storybook testing. Here is the flow of this popup:
1. The user pastes a google sheet link in.
a. They can either own the sheet or just have access to it through their google account.
1. The user clicks Extract Data.
1. This sends a request to the backend to check if the user is already logged in through google. 
a. If so, respond to the frontend with a 200 or similar. Frontend then calls the endpoint in the next step to extract the data.
b. If not, then we create an auth url and send that to the frontend. The frontend opens a new tab (or popup) asking the user to consent our app for google so that we can read spreadsheets (as mentioned this is currently read only. We can add a write-request later on without hurting anything). If the user denies the consent form or closes the tab/popup, then we receive an error from the google request, and we display an error on the popup that the user has to accept the request for us to extract data, and to click Extract again to re-attempt. If the user accepts the consent form, then it redirects to the next endpoint for us (this is necessary so that the request token is never sent to the frontend for possible malicious interception).
1. Backend endpoint/socket: calls google's sheets api to extract the data and send it to the frontend.
a. Called by the frontend if we are already logged in to google.
b. Called by a google redirect if we just got the user's consent.
1. Normal flow from here now that we have the data in the form. 

In the case of a storybook that a dev is doing with a link from the above google drive, the same flow still basically applies, and then google would see that the dev's google account has access to the spreadsheet in the drive even though they don't own it. Additionally, all of the above flow is still necessary even if the user opens up maximum access on the spreadsheet for _anyone_ to be able to view their spreadsheet. In that scenario google still responds with 403 if the user has not gone through the above flow. 

I recognize you may not have needed to see the entire flow, but I figured it helps to have it mapped out ahead of the work, and we can rewrite it if any other roadblocks are hit. 

Thanks!

**Comment by ddfridley** [comment]
@ice1080 
Here is a rough draft swag at doing oauth2 with google with the socket-apis
I guarantee bugs and syntax errors in the code below.

client side:

YOUR_CLIENT_ID and YOUR_REDIRECT_URI are public. Even if we constructed the Authorization URI on the server and sent it to the client, those values would be visible. And the Authorization URI has to be accessed by the client, so the user gets the login window.

```js
import objectid from 'isomorphic-mongo-objectid'

function oauth2SignIn() {
    const uniqueId=objectid().toString() // a unique id for this auth request

    // Google's OAuth 2.0 endpoint for requesting an access token
    var oauth2Endpoint = 'https://accounts.google.com/o/oauth2/v2/auth';

    // Create element to open OAuth 2.0 endpoint in new window.
    // this form stuff cold probable be done in React but for now we just follow googles example
    var form = document.createElement('form');
    form.setAttribute('method', 'GET'); // Send as a GET request.
    form.setAttribute('action', oauth2Endpoint);

    // Parameters to pass to OAuth 2.0 endpoint.
    var params = {'client_id': YOUR_CLIENT_ID,
                  'redirect_uri': YOUR_REDIRECT_URI,
                  'scope': 'https://www.googleapis.com/auth/drive.metadata.readonly',
                  'state': uniqueId,
                  'include_granted_scopes': 'true',
                  'response_type': 'token'};

    // Add form parameters as hidden input values.
    for (var p in params) {
      var input = document.createElement('input');
      input.setAttribute('type', 'hidden');
      input.setAttribute('name', p);
      input.setAttribute('value', params[p]);
      form.appendChild(input);
    }

    // Add form to page and submit it to open the OAuth 2.0 endpoint.
    document.body.appendChild(form);
    form.submit();

    // my worry with the above is that we are going to get redirect off of this page. Like you were saying, maybe we need to do it in another tab or a pop up.  I know I have seen these auth windows popup somehow.

    // the uniqueId above, lets us associate the incoming oauth request with the socket-api call.
    socket.emit('get-ggl-drive-info, uniqueId, driveInfo=>console.info("driveInfo:",driveInfo))  // or do what we need to with the info
  }

```
socket-apis/get-ggl-drive-info.js
```
import {oauth2callbacks} from '../route/oauth2callback'

export default function getGglDriveInfo(uniqueId, cb){
    oauth2callbacks.push({uniqueId, oauth2Client=>{
        // Example of using Google Drive API to list filenames in user's Drive.
        const drive = google.drive('v3');
        drive.files.list({
          auth: oauth2Client,
          pageSize: 10,
          fields: 'nextPageToken, files(id, name)',
        }, (err1, res1) => {
          if (err1) {
                   cb() // let client know there was an error
                   return console.log('The API returned an error: ' + err1);
          }
          const files = res1.data.files;
          let driveInfo=[]
          if (files.length) {
            driveInfo=files.map((file) =>`${file.name} (${file.id})`);
            cb(driveInfo)
          } else {
            cb(driveInfo)
          }
        });
    })
}

```
routes/oauth2callback.js
```
const { google } = require('googleapis');

const oauth2callbacks=[]
export oauth2callbacks

function oauth2callback(req, res, next){
        if(!req.query.code) return next()
        if(!req.query.state) return next()
        const item=oauth2callbacks.find(obj=>obj.uniqueId===req.query.state)
        if(!item) return next()
        const oauth2Client = new google.auth.OAuth2(
          process.env.YOUR_CLIENT_ID,
          process.env.YOUR_CLIENT_SECRET,
          process.env.YOUR_REDIRECT_URL
        );
        let { tokens } = await oauth2Client.getToken(req.query.code);
        oauth2Client.setCredentials(tokens);
        item.callback(oauth2Client)
}

export default function route() {
  this.app.get('/oauth2callback', oauth2callback)
}

```

**Comment by ice1080** [comment]
Thanks for this @ddfridley! This lines up with what I was originally thinking before our long discussions haha.
The main thing I didn't realize from the above is that express/node will keep objects in memory such as your above `const oauth2callbacks`, and that multiple files that import that will use the same pointer. I believe that solves the last piece of the puzzle that I was confused on. I will try that soon.

**Comment by ddfridley** [comment]
Oops, after you find the item you  have to remove it.
```
 const index=oauth2callbacks.findIndex(obj=>obj.uniqueId===req.query.state)
 if(index<0) return next()
const item=oauth2callbacks[index]
oauth2callbacks.splice(index,1)
```

**Comment by ice1080** [comment]
One more question on the oauth2callbacks object. Is this atomically safe in nodejs? i.e. if two processes are modifying the object at the same time, is it possible that splice could end up messing up the object?

**Comment by ice1080** [comment]
Now that I sent that, I just talked to someone else and they sent me this which helped answer my question. JS itself is single threaded, so the above use of the shared objects across multiple sessions is safe. Sorry for all the questions on this one!
https://stackoverflow.com/questions/49141259/does-a-nodejs-server-use-multithreading/49141596#49141596

**Comment by ddfridley** [comment]
I'm trying to run it, and having trouble with the authorization. Trying to run it from my windows PC.  How did you fill out this page:
![image](https://user-images.githubusercontent.com/3317487/169678014-c8b2e790-2de8-40f1-98be-31e935513954.png)

**Comment by ddfridley** [comment]
Working!

Authorized redirect URIs: http://localhost:3011/googleAuthRedirect

I had HOSTNAME set wrong, and then I didn't think to include the googleAuthRedirect part.

**Comment by ddfridley** [comment]
Now I'm getting an error "Unable to extract data from link. Please compare your document with the sample document."
Does this look right?: https://docs.google.com/spreadsheets/d/1hR3dQb3Giju27ssb3IReeRh_Q7VfdL26AWF8IvFV-o4/edit?usp=sharing

**Comment by ddfridley** [comment]
Resolved.  I needed to do this: 'Google Sheets API has not been used in project XXXXXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sheets.googleapis.com/overview?project=XXXXXXXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.'

**Comment by ice1080** [comment]
Ah interesting. I shall update the readme with that info in an upcoming commit!

**Comment by ddfridley** [comment]
I made changes to make the oauth part more generic. And tested them and put those changes in this branch: https://github.com/EnCiv/undebate-ssp/tree/oauth-separate so you can have a look.  I don't know an easy way to show you the diffs.  It's not a lot of changes, but it's to the files extract-sheet-data.js, is-signed-in-for-sheet.js, google-paste-sheets-popup.js, and google-auth-redirect.js. Maybe you can pull this branch and compare it to yours. 

I didn't want to change file names, but in my idea, is-signed-in-for-sheet would become get-oauth-redirect-url and google-auth-redirect would become oauth-redirect

let me know if you want me to walk through it.

it's not necessary that we go in this direction at this time, but I wanted to show you the thinking.

**Comment by ice1080** [comment]
I think that definitely makes sense, and will probably be easier now than later. Working on the merge now. I also most likely will not be able to make the meeting tomorrow night but am getting close to having this in a more workable condition.

**Comment by ice1080** [comment]
Just about done with it overall; calling it done for tonight. I need to test with some actual socket users, which I assume I get by creating a user on the /join page (or whichever it was). I'll clean up the console logs, and the last thing is adding the link to the spreadsheet in google drive you mentioned above. I should have this done by later tomorrow night!

**Comment by ddfridley** [comment]
Yes /join is where to go. I admire how informative your commit messages are.  I doubt mine are.  I was thinking it might be nice to future developers to add the url[s] to the spreadsheets into your webComponent/qa-... so they can just copy and paste them in, or click on them to open them.

Thanks a whole bunch for this effort.  Have a great vacation.

**Comment by ice1080** [comment]
Ah good idea. I'll move them into that Google drive link so they're owned by that, and add them to the QA component.
